github:
#  organization: micronaut-projects
  repo: lovefood
  username : Hemanth-the-coder

micronaut:

  codec:
    json:
      additional-types:
        - application/vnd.github.v3+json
  http:
    client:
      versioning:
        default:
          headers:
            - 'Accept-Version'
            - 'X-API-VERSION'
    services:
      github:
        url: https://api.github.com
      versioning:
        url: http://localhost:8081

  server:
    port: 5000
